# Generated by Django 4.0 on 2023-11-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ポケモンの名前')),
                ('category', models.CharField(choices=[('赤・緑', '赤・緑'), ('金・銀', '金・銀'), ('ルビー・サファイア・エメラルド', 'ルビー・サファイア・エメラルド'), ('ダイヤモンド・パール・プラチナ', 'ダイヤモンド・パール・プラチナ'), ('ブラック・ホワイト', 'ブラック・ホワイト'), ('X・Y', 'X・Y'), ('サン・ムーン', 'サン・ムーン'), ('ソード・シールド・Legendsアルセウス', 'ソード・シールド・Legendsアルセウス'), ('スカーレット・バイオレット', 'スカーレット・バイオレット')], max_length=50, verbose_name='ポケモンの世代')),
            ],
        ),
        migrations.CreateModel(
            name='Pokepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('赤・緑', '赤・緑'), ('金・銀', '金・銀'), ('ルビー・サファイア・エメラルド', 'ルビー・サファイア・エメラルド'), ('ダイヤモンド・パール・プラチナ', 'ダイヤモンド・パール・プラチナ'), ('ブラック・ホワイト', 'ブラック・ホワイト'), ('X・Y', 'X・Y'), ('サン・ムーン', 'サン・ムーン'), ('ソード・シールド・Legendsアルセウス', 'ソード・シールド・Legendsアルセウス'), ('スカーレット・バイオレット', 'スカーレット・バイオレット')], max_length=50, verbose_name='pokeage')),
                ('image', models.ImageField(upload_to='pokeimage', verbose_name='pokeimage')),
                ('type', models.CharField(max_length=20, verbose_name='poketype')),
                ('detail', models.TextField(verbose_name='pokedetail')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pokebook.pokename', verbose_name='ポケモンの名前')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser', verbose_name='ユーザー')),
            ],
        ),
    ]
