# Generated by Django 4.0 on 2023-11-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokepost',
            name='type',
        ),
        migrations.AddField(
            model_name='pokepost',
            name='type1',
            field=models.CharField(choices=[('', '選択してください'), ('ノーマル', 'ノーマル'), ('ほのお', 'ほのお'), ('みず', 'みず'), ('くさ', 'くさ'), ('でんき', 'でんき'), ('こおり', 'こおり'), ('かくとう', 'かくとう'), ('どく', 'どく'), ('じめん', 'じめん'), ('ひこう', 'ひこう'), ('エスパー', 'エスパー'), ('むし', 'むし'), ('いわ', 'いわ'), ('ゴースト', 'ゴースト'), ('ドラゴン', 'ドラゴン'), ('あく', 'あく'), ('はがね', 'はがね'), ('フェアリー', 'フェアリー')], default='', max_length=20, verbose_name='poketype1'),
        ),
        migrations.AddField(
            model_name='pokepost',
            name='type2',
            field=models.CharField(blank=True, choices=[('', '選択してください'), ('ノーマル', 'ノーマル'), ('ほのお', 'ほのお'), ('みず', 'みず'), ('くさ', 'くさ'), ('でんき', 'でんき'), ('こおり', 'こおり'), ('かくとう', 'かくとう'), ('どく', 'どく'), ('じめん', 'じめん'), ('ひこう', 'ひこう'), ('エスパー', 'エスパー'), ('むし', 'むし'), ('いわ', 'いわ'), ('ゴースト', 'ゴースト'), ('ドラゴン', 'ドラゴン'), ('あく', 'あく'), ('はがね', 'はがね'), ('フェアリー', 'フェアリー')], default='', max_length=20, null=True, verbose_name='poketype2'),
        ),
    ]
