# Generated by Django 4.0 on 2023-11-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebook', '0002_remove_pokepost_type_pokepost_type1_pokepost_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokepost',
            name='num',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='図鑑ナンバー'),
        ),
        migrations.AlterField(
            model_name='pokename',
            name='category',
            field=models.CharField(choices=[('赤・緑', '赤・緑'), ('金・銀', '金・銀'), ('ルビー・サファイア・エメラルド', 'ルビー・サファイア・エメラルド'), ('ダイヤモンド・パール・プラチナ', 'ダイヤモンド・パール・プラチナ'), ('ブラック・ホワイト', 'ブラック・ホワイト'), ('X・Y', 'X・Y'), ('サン・ムーン', 'サン・ムーン'), ('ソード・シールド・Legendsアルセウス', 'ソード・シールド・Legendsアルセウス'), ('スカーレット・バイオレット', 'スカーレット・バイオレッ')], max_length=50, verbose_name='ポケモンの世代'),
        ),
        migrations.AlterField(
            model_name='pokepost',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ポケモンの名前'),
        ),
        migrations.AlterField(
            model_name='pokepost',
            name='type2',
            field=models.CharField(blank=True, choices=[('', 'なし'), ('ノーマル', 'ノーマル'), ('ほのお', 'ほのお'), ('みず', 'みず'), ('くさ', 'くさ'), ('でんき', 'でんき'), ('こおり', 'こおり'), ('かくとう', 'かくとう'), ('どく', 'どく'), ('じめん', 'じめん'), ('ひこう', 'ひこう'), ('エスパー', 'エスパー'), ('むし', 'むし'), ('いわ', 'いわ'), ('ゴースト', 'ゴースト'), ('ドラゴン', 'ドラゴン'), ('あく', 'あく'), ('はがね', 'はがね'), ('フェアリー', 'フェアリー')], default='', max_length=20, null=True, verbose_name='poketype2'),
        ),
    ]
