# Generated by Django 4.0 on 2023-11-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebook', '0003_pokepost_num_alter_pokename_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokepost',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pokeimages', verbose_name='pokeimage2'),
        ),
        migrations.AlterField(
            model_name='pokepost',
            name='image',
            field=models.ImageField(upload_to='pokeimages', verbose_name='pokeimage'),
        ),
    ]
